### ISSUE TITLE
Inconsistent naming when loading a model

### ISSUE THREAD

**Issue by BenjaminNavarro** [CoppeliaRobotics/v_repExtRemoteApi#3]
I noticed that loading a model from the V-REP interface or from the remote API doesn't lead to the same result if the model is imported more than one. 

Let's say we import the `KUKA LBR4+.ttm` twice. If we do this from the V-REP menus, we get two robots and the second one has a trailing `#0` for each object (e.g. LBR4p_joint1 -> LBR4p_joint1#0). But if we do this from the remote API, instead of appending a suffix the numbering changes (e.g. LBR4p_joint1 -> LBR4p_joint8).

I'm not sure if it's a regression (I'm pretty sure it was ok with 3.4.0) or something desired but I highly prefer the suffix way of doing it, it makes the dynamic loading and interfacing of models much easier.

As a side note, I'm not using the `KUKA LBR4+.ttm` model in my tests but a modified version of it but I don't think it could have an influence.

**Comment by Coppelia** [comment]
Hello Benjamin,
can you confirm that the problem happens also with the KUKA LBR4+ model? Because I cannot reproduce the issue you are having. Maybe it is your model: when loading or copying a model (or models, objects, etc.) into the scene, if any of the objects to be added to the scene contains an associated script, then you will always have a "#"-suffix, in order to keep the scripts operational on their respective objects. If none of the objects to be added contains an associated script, then object names will be adjusted to avoid conflicts with other objects only.

**Comment by BenjaminNavarro** [comment]
That's probably it! I removed the script because I don't need it so that would explain the difference. I guess I can put an empty script but wouldn't be better to have this behavior configurable? When we load a model we can use a second option bit which kind of renaming we prefer

**Comment by Coppelia** [comment]
You are right. In next release you'll be able to append your model name with "@copy" to trigger the desired behaviour. In the mean time you'll have to use the empty script workaround.

**Comment by BenjaminNavarro** [comment]
Ok no problem, thanks
